services:
  prometheus:
   image: prom/prometheus
   ports:
    - "9090:9090"
   volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
   image: prom/node-exporter
   ports:
   - "9100:9100"
  grafana:
   image: grafana/grafana-oss
   ports:
    - "3000:3000"

networks:
 monitoring: